#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Icons
# iDIR="$HOME/.config/bspwm/assets"
iDIR="$HOME/.config/swaync/icons"
notify_cmd='dunstify -u low -h string:x-dunst-stack-tag:obvolume'

# Get Volume
get_volume() {
    pamixer --get-volume-human | sed 's/%//'
}

# Get icons
get_icon() {
    current=$(get_volume)
    if [[ "$current" == "Muted" ]]; then
        echo "$iDIR/volume-mute.png"
    elif [[ "${current%\%}" -le 30 ]]; then
        echo "$iDIR/volume-low.png"
    elif [[ "${current%\%}" -le 60 ]]; then
        echo "$iDIR/volume-mid.png"
    else
        echo "$iDIR/volume-high.png"
    fi
}

# Notify
notify_user() {
    ${notify_cmd} -i "$icon" "Volume : $(get_volume)%"
}

# Increase Volume
inc_volume() {
    [[ $(pamixer --get-mute) == true ]] && pamixer -u
    pamixer --allow-boost --set-limit 150 -i 5 && get_icon && notify_user
}

# Decrease Volume
dec_volume() {
    [[ $(pamixer --get-mute) == true ]] && pamixer -u
    pamixer --allow-boost --set-limit 150 -d 5 && get_icon && notify_user
}

# Toggle Mute
toggle_mute() {
    if [[ $(pamixer --get-mute) == false ]]; then
        pamixer --toggle-mute && ${notify_cmd} -i "$iDIR/mute.png" "Mute"
    else
        pamixer --toggle-mute && get_icon && ${notify_cmd} -i "$icon" "Unmute"
    fi
}


# Toggle Mic
toggle_mic() {
    if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
        pamixer --default-source -m && notify-send -e -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
    elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
        pamixer -u --default-source u && notify-send -e -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
    fi
}
# Get Mic Icon
get_mic_icon() {
    current=$(pamixer --default-source --get-volume)
    if [[ "$current" -eq "0" ]]; then
        echo "$iDIR/microphone-mute.png"
    else
        echo "$iDIR/microphone.png"
    fi
}

# Get Microphone Volume
get_mic_volume() {
    volume=$(pamixer --default-source --get-volume)
    if [[ "$volume" -eq "0" ]]; then
        echo "Muted"
    else
        echo "$volume%"
    fi
}

# Notify for Microphone
notify_mic_user() {
    volume=$(get_mic_volume)
    icon=$(get_mic_icon)
    notify-send -e -h int:value:"$volume" -h "string:x-canonical-private-synchronous:volume_notif" -u low -i "$icon" "Mic-Level: $volume"
}

# Increase MIC Volume
inc_mic_volume() {
    if [ "$(pamixer --default-source --get-mute)" == "true" ]; then
        toggle_mic
    else
        pamixer --default-source -i 5 && notify_mic_user
    fi
}

# Decrease MIC Volume
dec_mic_volume() {
    if [ "$(pamixer --default-source --get-mute)" == "true" ]; then
        toggle-mic
    else
        pamixer --default-source -d 5 && notify_mic_user
    fi
}


# Execute accordingly
if [[ -x $(which pamixer) ]]; then
    if [[ "$1" == "--get" ]]; then
        get_volume
    elif [[ "$1" == "--inc" ]]; then
        inc_volume
    elif [[ "$1" == "--dec" ]]; then
        dec_volume
    elif [[ "$1" == "--toggle" ]]; then
        toggle_mute
    elif [[ "$1" == "--toggle-mic" ]]; then
        toggle_mic
    elif [[ "$1" == "--get-icon" ]]; then
        get_icon
    elif [[ "$1" == "--get-mic-icon" ]]; then
        get_mic_icon
    elif [[ "$1" == "--mic-inc" ]]; then
        inc_mic_volume
    elif [[ "$1" == "--mic-dec" ]]; then
        dec_mic_volume
    else
        echo "$(get_volume)%"
    fi
else
    ${notify_cmd} "'pamixer' is not installed."
fi



